spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kcar?serverTimezone=Asia/Seoul&autoReconnect=true
    username: hyeonw
    password: hyeonw1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  servlet:
  #    multipart:
  #      enabled: true
  #      max-file-size: 200MB
  #      max-reauest-size: 215MB
  #      location: c:/img

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #                show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace